# Generated by Django 4.1.5 on 2023-01-31 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_music'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='music',
            options={'verbose_name': 'Продукты', 'verbose_name_plural': 'Продукты'},
        ),
    ]
